version:                "3"
services:
  datascience-notebook:
      image:            jupyter/datascience-notebook
      volumes:
        - /home/jacob/covid19:/home/jovyan/work
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container
      environment:
        - JUPYTER_ENABLE_LAB=yes 